from enum import Enum

class RelationshipType(str, Enum):
    MADRE = "madre"
    PADRE = "padre"
    GENITORE = "genitore"
    FRATELLO = "fratello"
    SORELLA = "sorella"
    FIGLIO = "figlio"
    FIGLIA = "figlia"
    AMICO = "amico"
    CONIUGE = "coniuge"
    PARTNER = "partner"
    ASSISTENTE = "assistente"
    MANAGER = "manager"
    ALTRO = "altro"
    COINQUILINO = "coinquilino"
    MEDICO = "medico"
    EMERGENZA = "emergenza"
    MEMBRO_DELLA_FAMIGLIA = "membro della famiglia"
    DOCENTE = "docente"
    BADANTE = "badante"
    TUTORE = "tutore"
    ASSISTENTE_SOCIALE = "assistente sociale"
    SCUOLA = "scuola"
    CENTRO_DIURNO = "centro diurno"
